apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-app-config
data:
  # Application environment variables
  NODE_ENV: "development"
  NEXT_PUBLIC_HOST: "http://localhost:3000"
  CHOKIDAR_USEPOLLING: "true"