apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-prod

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - mongo-dep.yaml
  - secrets.yaml
  - hpa.yaml
  - ingress.yaml
  